name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-server:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} for Server
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies (Server)
      run: npm ci
      working-directory: Server
    - run: |
        touch Server/.env
        echo "${{ secrets.SKLAMA_ENV_FILE }}" > Server/.env

  build-skailama:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} for Skailama
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies (Skailama)
      run: npm ci
      working-directory: Skailama
    - run: |
        touch Skailama/.env
        echo "${{ secrets.SKLAMA_ENV_FILE }}" > Skailama/.env
