name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-env-server:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file for Server
      run: |
        mkdir -p Skailama/Skailama/Server
        echo "${{ secrets.SKLAMA_ENV_FILE }}" > Skailama/Skailama/Server/.env
